// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    TaskItemComponent: typeof import('./src/components/TaskItemComponent.vue')['default']
    TaskListComponent: typeof import('./src/components/TaskListComponent.vue')['default']
  }
}

export { }
